// ABOUTME: Heroicons library configuration for React components
// ABOUTME: Exports commonly used Heroicons for consistent use throughout the app

// Outline icons (24x24)
export {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  AtSymbolIcon,
  BackwardIcon,
  BarsIcon,
  BeakerIcon,
  BellIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  CameraIcon,
  ChatBubbleLeftIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardIcon,
  ClockIcon,
  CloudIcon,
  CodeBracketIcon,
  CogIcon,
  ComputerDesktopIcon,
  DocumentIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  ForwardIcon,
  GlobeAltIcon,
  HandRaisedIcon,
  HeartIcon,
  HomeIcon,
  InformationCircleIcon,
  KeyIcon,
  LightBulbIcon,
  LinkIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MicrophoneIcon,
  MusicalNoteIcon,
  PaperAirplaneIcon,
  PauseIcon,
  PhoneIcon,
  PhotoIcon,
  PlayIcon,
  PlusIcon,
  PowerIcon,
  QuestionMarkCircleIcon,
  RocketLaunchIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  StarIcon,
  StopIcon,
  SunIcon,
  TagIcon,
  TrashIcon,
  UserIcon,
  VideoCameraIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';

// Solid icons (24x24)
export {
  AcademicCapIcon as AcademicCapIconSolid,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconSolid,
  ArchiveBoxIcon as ArchiveBoxIconSolid,
  ArrowDownIcon as ArrowDownIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowRightIcon as ArrowRightIconSolid,
  ArrowUpIcon as ArrowUpIconSolid,
  AtSymbolIcon as AtSymbolIconSolid,
  BackwardIcon as BackwardIconSolid,
  BarsIcon as BarsIconSolid,
  BeakerIcon as BeakerIconSolid,
  BellIcon as BellIconSolid,
  BoltIcon as BoltIconSolid,
  BookOpenIcon as BookOpenIconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  CalendarIcon as CalendarIconSolid,
  CameraIcon as CameraIconSolid,
  ChatBubbleLeftIcon as ChatBubbleLeftIconSolid,
  CheckIcon as CheckIconSolid,
  ChevronDownIcon as ChevronDownIconSolid,
  ChevronLeftIcon as ChevronLeftIconSolid,
  ChevronRightIcon as ChevronRightIconSolid,
  ChevronUpIcon as ChevronUpIconSolid,
  ClipboardIcon as ClipboardIconSolid,
  ClockIcon as ClockIconSolid,
  CloudIcon as CloudIconSolid,
  CodeBracketIcon as CodeBracketIconSolid,
  CogIcon as CogIconSolid,
  ComputerDesktopIcon as ComputerDesktopIconSolid,
  DocumentIcon as DocumentIconSolid,
  EllipsisHorizontalIcon as EllipsisHorizontalIconSolid,
  EllipsisVerticalIcon as EllipsisVerticalIconSolid,
  EyeIcon as EyeIconSolid,
  EyeSlashIcon as EyeSlashIconSolid,
  FolderIcon as FolderIconSolid,
  ForwardIcon as ForwardIconSolid,
  GlobeAltIcon as GlobeAltIconSolid,
  HandRaisedIcon as HandRaisedIconSolid,
  HeartIcon as HeartIconSolid,
  HomeIcon as HomeIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  KeyIcon as KeyIconSolid,
  LightBulbIcon as LightBulbIconSolid,
  LinkIcon as LinkIconSolid,
  LockClosedIcon as LockClosedIconSolid,
  MagnifyingGlassIcon as MagnifyingGlassIconSolid,
  MapIcon as MapIconSolid,
  MicrophoneIcon as MicrophoneIconSolid,
  MusicalNoteIcon as MusicalNoteIconSolid,
  PaperAirplaneIcon as PaperAirplaneIconSolid,
  PauseIcon as PauseIconSolid,
  PhoneIcon as PhoneIconSolid,
  PhotoIcon as PhotoIconSolid,
  PlayIcon as PlayIconSolid,
  PlusIcon as PlusIconSolid,
  PowerIcon as PowerIconSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleIconSolid,
  RocketLaunchIcon as RocketLaunchIconSolid,
  ServerIcon as ServerIconSolid,
  ShareIcon as ShareIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  SparklesIcon as SparklesIconSolid,
  SpeakerWaveIcon as SpeakerWaveIconSolid,
  SpeakerXMarkIcon as SpeakerXMarkIconSolid,
  StarIcon as StarIconSolid,
  StopIcon as StopIconSolid,
  SunIcon as SunIconSolid,
  TagIcon as TagIconSolid,
  TrashIcon as TrashIconSolid,
  UserIcon as UserIconSolid,
  VideoCameraIcon as VideoCameraIconSolid,
  WrenchScrewdriverIcon as WrenchScrewdriverIconSolid,
  XMarkIcon as XMarkIconSolid,
} from '@heroicons/react/24/solid';

// Mini icons (20x20)
export {
  AcademicCapIcon as AcademicCapIconMini,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconMini,
  ArchiveBoxIcon as ArchiveBoxIconMini,
  ArrowDownIcon as ArrowDownIconMini,
  ArrowLeftIcon as ArrowLeftIconMini,
  ArrowRightIcon as ArrowRightIconMini,
  ArrowUpIcon as ArrowUpIconMini,
  AtSymbolIcon as AtSymbolIconMini,
  BackwardIcon as BackwardIconMini,
  BarsIcon as BarsIconMini,
  BeakerIcon as BeakerIconMini,
  BellIcon as BellIconMini,
  BoltIcon as BoltIconMini,
  BookOpenIcon as BookOpenIconMini,
  BuildingOfficeIcon as BuildingOfficeIconMini,
  CalendarIcon as CalendarIconMini,
  CameraIcon as CameraIconMini,
  ChatBubbleLeftIcon as ChatBubbleLeftIconMini,
  CheckIcon as CheckIconMini,
  ChevronDownIcon as ChevronDownIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ChevronRightIcon as ChevronRightIconMini,
  ChevronUpIcon as ChevronUpIconMini,
  ClipboardIcon as ClipboardIconMini,
  ClockIcon as ClockIconMini,
  CloudIcon as CloudIconMini,
  CodeBracketIcon as CodeBracketIconMini,
  CogIcon as CogIconMini,
  ComputerDesktopIcon as ComputerDesktopIconMini,
  DocumentIcon as DocumentIconMini,
  EllipsisHorizontalIcon as EllipsisHorizontalIconMini,
  EllipsisVerticalIcon as EllipsisVerticalIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  FolderIcon as FolderIconMini,
  ForwardIcon as ForwardIconMini,
  GlobeAltIcon as GlobeAltIconMini,
  HandRaisedIcon as HandRaisedIconMini,
  HeartIcon as HeartIconMini,
  HomeIcon as HomeIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  KeyIcon as KeyIconMini,
  LightBulbIcon as LightBulbIconMini,
  LinkIcon as LinkIconMini,
  LockClosedIcon as LockClosedIconMini,
  MagnifyingGlassIcon as MagnifyingGlassIconMini,
  MapIcon as MapIconMini,
  MicrophoneIcon as MicrophoneIconMini,
  MusicalNoteIcon as MusicalNoteIconMini,
  PaperAirplaneIcon as PaperAirplaneIconMini,
  PauseIcon as PauseIconMini,
  PhoneIcon as PhoneIconMini,
  PhotoIcon as PhotoIconMini,
  PlayIcon as PlayIconMini,
  PlusIcon as PlusIconMini,
  PowerIcon as PowerIconMini,
  QuestionMarkCircleIcon as QuestionMarkCircleIconMini,
  RocketLaunchIcon as RocketLaunchIconMini,
  ServerIcon as ServerIconMini,
  ShareIcon as ShareIconMini,
  ShieldCheckIcon as ShieldCheckIconMini,
  SparklesIcon as SparklesIconMini,
  SpeakerWaveIcon as SpeakerWaveIconMini,
  SpeakerXMarkIcon as SpeakerXMarkIconMini,
  StarIcon as StarIconMini,
  StopIcon as StopIconMini,
  SunIcon as SunIconMini,
  TagIcon as TagIconMini,
  TrashIcon as TrashIconMini,
  UserIcon as UserIconMini,
  VideoCameraIcon as VideoCameraIconMini,
  WrenchScrewdriverIcon as WrenchScrewdriverIconMini,
  XMarkIcon as XMarkIconMini,
} from '@heroicons/react/20/solid';
