// ABOUTME: Coverage for the host/spawn/env outbound RPC hook
// in JobManager.createJob. Verifies that the embedder-supplied env is
// merged into the delegate spawn's executionEnv with strict validation
// (POSIX-shape names) and conflict resolution (lace-managed names win).

import { describe, it, expect, vi } from 'vitest';
import { JobManager, type JobManagerDeps } from '../job-manager';
import type { RuntimeExecutionBinding } from '@lace/agent/tools/runtime/types';

const PARENT_SESSION_ID = 'sess_parent00000000';

function makeContainerBinding(): RuntimeExecutionBinding {
  return {
    schemaVersion: 1,
    identity: { runtimeId: 'rt_host_spawn_env_test' },
    toolRuntime: {
      type: 'container',
      spec: {
        name: 'spec-host-spawn-env',
        image: 'test:latest',
        workingDirectory: '/work',
        mounts: [],
      },
      cwd: '/work',
    },
  };
}

function createDeps(overrides: Partial<JobManagerDeps> = {}): JobManagerDeps {
  return {
    getActiveSession: vi.fn().mockReturnValue({
      sessionId: PARENT_SESSION_ID,
      dir: '/tmp/test-host-spawn-env',
    }),
    persistEvent: vi.fn().mockResolvedValue(undefined),
    emitUpdate: vi.fn().mockResolvedValue(undefined),
    runShellProcess: vi.fn(),
    runSubagentProcess: vi.fn(),
    ...overrides,
  };
}

function delegateOptions() {
  return {
    prompt: 'do work',
    persona: 'shell',
    runtimeBinding: makeContainerBinding(),
    containerSpecName: 'spec-host-spawn-env',
    containerExecutionIdentity: { tokenEnvName: 'SEN_AGENT_TOKEN' },
  };
}

describe('JobManager.createJob — host/spawn/env merge', () => {
  it('merges embedder-supplied env vars into the spawn executionEnv', async () => {
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({
      HTTPBIN_BEARER_TEST: 'sen-placeholder-abc123',
      CUSTOM_VAR: 'hello',
    });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    expect(fetchEmbedderSpawnEnv).toHaveBeenCalledOnce();
    expect(fetchEmbedderSpawnEnv).toHaveBeenCalledWith({
      jobId: job.jobId,
      persona: 'shell',
      parentSessionId: PARENT_SESSION_ID,
      runtimeId: 'rt_host_spawn_env_test',
    });

    expect(job.executionEnv).toBeDefined();
    // The base SEN_AGENT_TOKEN must still be present, generated by lace.
    expect(job.executionEnv?.SEN_AGENT_TOKEN).toEqual(expect.any(String));
    expect(job.executionEnv?.SEN_AGENT_TOKEN).not.toEqual('');
    // The embedder placeholders are merged.
    expect(job.executionEnv?.HTTPBIN_BEARER_TEST).toBe('sen-placeholder-abc123');
    expect(job.executionEnv?.CUSTOM_VAR).toBe('hello');
  });

  it('does not call the embedder for shell jobs', async () => {
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({ X: 'y' });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    await manager.createJob('shell', { command: 'echo hi' });

    expect(fetchEmbedderSpawnEnv).not.toHaveBeenCalled();
  });

  it('does not call the embedder when there is no container execution context', async () => {
    // No containerExecutionIdentity → buildContainerExecutionContext returns
    // undefined, so the embedder hook is skipped.
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({ X: 'y' });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    await manager.createJob('delegate', {
      prompt: 'do work',
      persona: 'shell',
      runtimeBinding: makeContainerBinding(),
    });

    expect(fetchEmbedderSpawnEnv).not.toHaveBeenCalled();
  });

  it('proceeds with base executionEnv when the embedder method is unimplemented (rejects)', async () => {
    const fetchEmbedderSpawnEnv = vi
      .fn()
      .mockRejectedValue({ code: -32601, message: 'Method not found' });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    expect(fetchEmbedderSpawnEnv).toHaveBeenCalledOnce();
    expect(job.executionEnv).toBeDefined();
    expect(job.executionEnv?.SEN_AGENT_TOKEN).toEqual(expect.any(String));
    // No extra vars were added.
    expect(Object.keys(job.executionEnv ?? {})).toEqual(['SEN_AGENT_TOKEN']);
    // Spawn was NOT blocked: subagent runner was invoked.
    expect(deps.runSubagentProcess).toHaveBeenCalledOnce();
  });

  it('proceeds with base executionEnv when no fetchEmbedderSpawnEnv dep is provided', async () => {
    const deps = createDeps();
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    expect(job.executionEnv).toBeDefined();
    expect(Object.keys(job.executionEnv ?? {})).toEqual(['SEN_AGENT_TOKEN']);
  });

  it('drops env vars with malformed names (does not match POSIX shape)', async () => {
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({
      VALID_NAME: 'ok',
      'bad-name': 'dropped-1',
      '': 'dropped-2',
      lowercase: 'kept-3',
      '1STARTS_WITH_DIGIT': 'dropped-4',
      ANOTHER_VALID: 'ok-2',
      https_proxy: 'kept-https-proxy',
    });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    expect(job.executionEnv?.VALID_NAME).toBe('ok');
    expect(job.executionEnv?.ANOTHER_VALID).toBe('ok-2');
    // Lowercase env var names are valid POSIX and conventional for
    // proxy vars (https_proxy, no_proxy, etc.) — keep them.
    expect(job.executionEnv?.lowercase).toBe('kept-3');
    expect(job.executionEnv?.https_proxy).toBe('kept-https-proxy');
    expect(job.executionEnv?.['bad-name']).toBeUndefined();
    expect(job.executionEnv?.['']).toBeUndefined();
    expect(job.executionEnv?.['1STARTS_WITH_DIGIT']).toBeUndefined();
  });

  it('ignores attempts to override SEN_AGENT_TOKEN (lace-managed)', async () => {
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({
      SEN_AGENT_TOKEN: 'attacker-controlled-token',
      OTHER_VAR: 'kept',
    });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    // The lace-generated token must survive untouched.
    expect(job.executionEnv?.SEN_AGENT_TOKEN).not.toBe('attacker-controlled-token');
    expect(job.executionEnv?.SEN_AGENT_TOKEN).toEqual(expect.any(String));
    // The non-colliding var is kept.
    expect(job.executionEnv?.OTHER_VAR).toBe('kept');
  });

  it('drops non-string values', async () => {
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({
      KEEP_THIS: 'good',
      // The wire schema validates this on the embedder side, but we belt-and-
      // suspenders the merger too in case the host returns a malformed object.
      DROP_THIS_NUMBER: 42 as unknown as string,
      DROP_THIS_NULL: null as unknown as string,
      DROP_THIS_OBJECT: { nested: 'no' } as unknown as string,
    });
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    expect(job.executionEnv?.KEEP_THIS).toBe('good');
    expect(job.executionEnv?.DROP_THIS_NUMBER).toBeUndefined();
    expect(job.executionEnv?.DROP_THIS_NULL).toBeUndefined();
    expect(job.executionEnv?.DROP_THIS_OBJECT).toBeUndefined();
  });

  it('omits runtimeId from the request when the binding has none', async () => {
    const fetchEmbedderSpawnEnv = vi.fn().mockResolvedValue({});
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const bindingWithoutRuntimeId: RuntimeExecutionBinding = {
      schemaVersion: 1,
      identity: {},
      toolRuntime: {
        type: 'container',
        spec: {
          name: 'spec-host-spawn-env',
          image: 'test:latest',
          workingDirectory: '/work',
          mounts: [],
        },
        cwd: '/work',
      },
    };

    await manager.createJob('delegate', {
      prompt: 'do work',
      persona: 'shell',
      runtimeBinding: bindingWithoutRuntimeId,
      containerSpecName: 'spec-host-spawn-env',
      containerExecutionIdentity: { tokenEnvName: 'SEN_AGENT_TOKEN' },
    });

    expect(fetchEmbedderSpawnEnv).toHaveBeenCalledOnce();
    const call = fetchEmbedderSpawnEnv.mock.calls[0][0] as Record<string, unknown>;
    expect(call).not.toHaveProperty('runtimeId');
    expect(call.persona).toBe('shell');
    expect(call.parentSessionId).toBe(PARENT_SESSION_ID);
  });

  it('handles a non-object response gracefully (logs and proceeds)', async () => {
    const fetchEmbedderSpawnEnv = vi
      .fn()
      .mockResolvedValue('not-an-object' as unknown as Record<string, string>);
    const deps = createDeps({ fetchEmbedderSpawnEnv });
    const manager = new JobManager(deps);

    const { job } = await manager.createJob('delegate', delegateOptions());

    // Base env survives, no extras merged.
    expect(Object.keys(job.executionEnv ?? {})).toEqual(['SEN_AGENT_TOKEN']);
    expect(deps.runSubagentProcess).toHaveBeenCalledOnce();
  });
});
