// ABOUTME: WorkspaceSessionId validation for supervisor-backed web sessions
// ABOUTME: WorkspaceSessionId is an opaque identifier generated by the supervisor store

import { z } from 'zod';

export const WorkspaceSessionIdSchema = z.string().regex(/^ws_[0-9a-f-]{36}$/);

export function isWorkspaceSessionId(value: string): boolean {
  return WorkspaceSessionIdSchema.safeParse(value).success;
}
