// FontAwesome configuration for React components
import { config } from '@fortawesome/fontawesome-svg-core';

// Prevent FontAwesome from adding CSS since we'll import it manually
config.autoAddCss = false;

// Export all the icons we need for easy importing
export {
  faSearch,
  faTerminal,
  faTasks,
  faFolder,
  faFolderOpen,
  faMicrophone,
  faPaperPlane,
  faPaperclip,
  faBars,
  faTimes,
  faComments,
  faPlus,
  faCheck,
  faCog,
  faFileCode,
  faUser,
  faSignOutAlt,
  // Additional icons for other components
  faCrown,
  faRobot,
  faInfoCircle,
  faCreditCard,
  faImages,
  faFileAlt,
  faFile,
  faImage,
  faFileExcel,
  faFolderPlus,
  faShare,
  faEdit,
  faCheckCircle,
  faTable,
  faMinus,
  faPlug,
  faPlay,
  faStop,
  faServer,
  faTools,
  faEye,
  faColumns,
  faList,
  faCopy,
  faExpand,
  faCompress,
  // Navigation icons for NavigationButton component
  faHome,
  faBell,
  faHeart,
  faBookmark,
  faChartBar as faChart,
  // Additional icons used in stories and components
  faComment,
  faEllipsisV,
  faTrash,
  faHistory,
  faInbox,
  faStar,
  faReply,
  faFileText,
  faExternalLinkAlt,
  faChevronDown,
  faChevronRight,
  faCode,
  faQuestion,
  faFlag,
  faClipboard,
  faClock,
  faSave,
  faDownload,
  faGlobe,
  faExclamationTriangle,
  faSpinner,
  faChevronLeft,
  faChevronUp,
  faWaveSquare,
  faVolumeHigh,
  // Error display icons (faExclamationTriangle and faClock already imported above)
  faRedo,
  faInfo,
  faSquare,
  // Debug panel icons
  faBug,
  faXmark as faX,
  faStream,
  faCircle,
  faPause,
  faFilter,
  faNewspaper,
} from '@fortawesome/free-solid-svg-icons';

// Re-export faXmark as faXmark for consistency
export { faXmark } from '@fortawesome/free-solid-svg-icons';
