// ABOUTME: Tests for web-internal event types generated by the web UI
// These tests verify that web events are properly structured and typed

import { describe, it, expect } from 'vitest';
import type {
  WebEvent,
  UserMessageEvent,
  AgentStateChangeEvent,
  AgentSpawnedEvent,
} from '@lace/web/types/web-events';

describe('Web Internal Event Types', () => {
  it('should create UserMessageEvent', () => {
    const event: UserMessageEvent = {
      id: 'evt_123',
      timestamp: new Date(),
      type: 'USER_MESSAGE',
      data: 'Hello',
      workspaceSessionId: 'ws_123',
      agentSessionId: 'sess_123',
    };

    expect(event.type).toBe('USER_MESSAGE');
    expect(event.data).toBe('Hello');
  });

  it('should create AgentStateChangeEvent', () => {
    const event: AgentStateChangeEvent = {
      id: 'evt_456',
      timestamp: new Date(),
      type: 'AGENT_STATE_CHANGE',
      data: {
        agentSessionId: 'sess_123',
        previousState: 'idle',
        newState: 'thinking',
      },
      workspaceSessionId: 'ws_123',
      agentSessionId: 'sess_123',
    };

    expect(event.data.newState).toBe('thinking');
  });

  it('should discriminate web event types', () => {
    const event: WebEvent = {
      id: 'evt_789',
      timestamp: new Date(),
      type: 'AGENT_SPAWNED',
      data: {
        agentSessionId: 'sess_new',
        parentSessionId: 'sess_parent',
      },
      workspaceSessionId: 'ws_123',
    };

    if (event.type === 'AGENT_SPAWNED') {
      expect(event.data.parentSessionId).toBe('sess_parent');
    }
  });

  it('should create AgentSpawnedEvent with optional fields', () => {
    const event: AgentSpawnedEvent = {
      id: 'evt_999',
      timestamp: new Date(),
      type: 'AGENT_SPAWNED',
      data: {
        agentSessionId: 'sess_spawn',
        taskId: 'task_123',
      },
      projectId: 'proj_123',
    };

    expect(event.type).toBe('AGENT_SPAWNED');
    expect(event.data.taskId).toBe('task_123');
  });
});
