// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/play": {
    params: {};
  };
  "/font-test": {
    params: {};
  };
  "/speech-demo": {
    params: {};
  };
  "/sentry-test": {
    params: {};
  };
  "/file-viewer": {
    params: {};
  };
  "/project/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/project/:projectId/session/:sessionId": {
    params: {
      "projectId": string;
      "sessionId": string;
    };
  };
  "/project/:projectId/session/:sessionId/agent/:agentId": {
    params: {
      "projectId": string;
      "sessionId": string;
      "agentId": string;
    };
  };
  "/api/health": {
    params: {};
  };
  "/api/events/stream": {
    params: {};
  };
  "/api/sentry-test": {
    params: {};
  };
  "/api/tunnel": {
    params: {};
  };
  "/api/agents/:agentId": {
    params: {
      "agentId": string;
    };
  };
  "/api/agents/:agentId/message": {
    params: {
      "agentId": string;
    };
  };
  "/api/agents/:agentId/stop": {
    params: {
      "agentId": string;
    };
  };
  "/api/agents/:agentId/history": {
    params: {
      "agentId": string;
    };
  };
  "/api/projects": {
    params: {};
  };
  "/api/projects/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/api/projects/:projectId/configuration": {
    params: {
      "projectId": string;
    };
  };
  "/api/projects/:projectId/environment": {
    params: {
      "projectId": string;
    };
  };
  "/api/projects/:projectId/templates": {
    params: {
      "projectId": string;
    };
  };
  "/api/projects/:projectId/templates/:templateId": {
    params: {
      "projectId": string;
      "templateId": string;
    };
  };
  "/api/projects/:projectId/sessions": {
    params: {
      "projectId": string;
    };
  };
  "/api/projects/:projectId/sessions/:sessionId": {
    params: {
      "projectId": string;
      "sessionId": string;
    };
  };
  "/api/projects/:projectId/sessions/:sessionId/tasks": {
    params: {
      "projectId": string;
      "sessionId": string;
    };
  };
  "/api/projects/:projectId/sessions/:sessionId/tasks/:taskId/notes": {
    params: {
      "projectId": string;
      "sessionId": string;
      "taskId": string;
    };
  };
  "/api/projects/:projectId/sessions/:sessionId/tasks/:taskId": {
    params: {
      "projectId": string;
      "sessionId": string;
      "taskId": string;
    };
  };
  "/api/sessions/:sessionId": {
    params: {
      "sessionId": string;
    };
  };
  "/api/sessions/:sessionId/agents": {
    params: {
      "sessionId": string;
    };
  };
  "/api/sessions/:sessionId/configuration": {
    params: {
      "sessionId": string;
    };
  };
  "/api/sessions/:sessionId/history": {
    params: {
      "sessionId": string;
    };
  };
  "/api/sessions/:sessionId/files": {
    params: {
      "sessionId": string;
    };
  };
  "/api/sessions/:sessionId/files/*": {
    params: {
      "sessionId": string;
      "*": string;
    };
  };
  "/api/provider/catalog": {
    params: {};
  };
  "/api/provider/instances": {
    params: {};
  };
  "/api/provider/instances/:instanceId": {
    params: {
      "instanceId": string;
    };
  };
  "/api/provider/instances/:instanceId/test": {
    params: {
      "instanceId": string;
    };
  };
  "/api/threads/:threadId/message": {
    params: {
      "threadId": string;
    };
  };
  "/api/threads/:threadId/approvals/pending": {
    params: {
      "threadId": string;
    };
  };
  "/api/threads/:threadId/approvals/:toolCallId": {
    params: {
      "threadId": string;
      "toolCallId": string;
    };
  };
  "/api/filesystem/list": {
    params: {};
  };
  "/api/debug/console": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs" | "/play" | "/font-test" | "/speech-demo" | "/sentry-test" | "/file-viewer" | "/project/:projectId" | "/project/:projectId/session/:sessionId" | "/project/:projectId/session/:sessionId/agent/:agentId" | "/api/health" | "/api/events/stream" | "/api/sentry-test" | "/api/tunnel" | "/api/agents/:agentId" | "/api/agents/:agentId/message" | "/api/agents/:agentId/stop" | "/api/agents/:agentId/history" | "/api/projects" | "/api/projects/:projectId" | "/api/projects/:projectId/configuration" | "/api/projects/:projectId/environment" | "/api/projects/:projectId/templates" | "/api/projects/:projectId/templates/:templateId" | "/api/projects/:projectId/sessions" | "/api/projects/:projectId/sessions/:sessionId" | "/api/projects/:projectId/sessions/:sessionId/tasks" | "/api/projects/:projectId/sessions/:sessionId/tasks/:taskId/notes" | "/api/projects/:projectId/sessions/:sessionId/tasks/:taskId" | "/api/sessions/:sessionId" | "/api/sessions/:sessionId/agents" | "/api/sessions/:sessionId/configuration" | "/api/sessions/:sessionId/history" | "/api/sessions/:sessionId/files" | "/api/sessions/:sessionId/files/*" | "/api/provider/catalog" | "/api/provider/instances" | "/api/provider/instances/:instanceId" | "/api/provider/instances/:instanceId/test" | "/api/threads/:threadId/message" | "/api/threads/:threadId/approvals/pending" | "/api/threads/:threadId/approvals/:toolCallId" | "/api/filesystem/list" | "/api/debug/console";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
  "routes/play.tsx": {
    id: "routes/play";
    page: "/play";
  };
  "routes/font-test.tsx": {
    id: "routes/font-test";
    page: "/font-test";
  };
  "routes/speech-demo.tsx": {
    id: "routes/speech-demo";
    page: "/speech-demo";
  };
  "routes/sentry-test.tsx": {
    id: "routes/sentry-test";
    page: "/sentry-test";
  };
  "routes/file-viewer.tsx": {
    id: "routes/file-viewer";
    page: "/file-viewer";
  };
  "routes/project.$projectId.tsx": {
    id: "routes/project.$projectId";
    page: "/project/:projectId";
  };
  "routes/project.$projectId.session.$sessionId.tsx": {
    id: "routes/project.$projectId.session.$sessionId";
    page: "/project/:projectId/session/:sessionId";
  };
  "routes/project.$projectId.session.$sessionId.agent.$agentId.tsx": {
    id: "routes/project.$projectId.session.$sessionId.agent.$agentId";
    page: "/project/:projectId/session/:sessionId/agent/:agentId";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.events.stream.ts": {
    id: "routes/api.events.stream";
    page: "/api/events/stream";
  };
  "routes/api.sentry-test.ts": {
    id: "routes/api.sentry-test";
    page: "/api/sentry-test";
  };
  "routes/api.tunnel.ts": {
    id: "routes/api.tunnel";
    page: "/api/tunnel";
  };
  "routes/api.agents.$agentId.ts": {
    id: "routes/api.agents.$agentId";
    page: "/api/agents/:agentId";
  };
  "routes/api.agents.$agentId.message.ts": {
    id: "routes/api.agents.$agentId.message";
    page: "/api/agents/:agentId/message";
  };
  "routes/api.agents.$agentId.stop.ts": {
    id: "routes/api.agents.$agentId.stop";
    page: "/api/agents/:agentId/stop";
  };
  "routes/api.agents.$agentId.history.ts": {
    id: "routes/api.agents.$agentId.history";
    page: "/api/agents/:agentId/history";
  };
  "routes/api.projects.ts": {
    id: "routes/api.projects";
    page: "/api/projects";
  };
  "routes/api.projects.$projectId.ts": {
    id: "routes/api.projects.$projectId";
    page: "/api/projects/:projectId";
  };
  "routes/api.projects.$projectId.configuration.ts": {
    id: "routes/api.projects.$projectId.configuration";
    page: "/api/projects/:projectId/configuration";
  };
  "routes/api.projects.$projectId.environment.ts": {
    id: "routes/api.projects.$projectId.environment";
    page: "/api/projects/:projectId/environment";
  };
  "routes/api.projects.$projectId.templates.ts": {
    id: "routes/api.projects.$projectId.templates";
    page: "/api/projects/:projectId/templates";
  };
  "routes/api.projects.$projectId.templates.$templateId.ts": {
    id: "routes/api.projects.$projectId.templates.$templateId";
    page: "/api/projects/:projectId/templates/:templateId";
  };
  "routes/api.projects.$projectId.sessions.ts": {
    id: "routes/api.projects.$projectId.sessions";
    page: "/api/projects/:projectId/sessions";
  };
  "routes/api.projects.$projectId.sessions.$sessionId.ts": {
    id: "routes/api.projects.$projectId.sessions.$sessionId";
    page: "/api/projects/:projectId/sessions/:sessionId";
  };
  "routes/api.projects.$projectId.sessions.$sessionId.tasks.ts": {
    id: "routes/api.projects.$projectId.sessions.$sessionId.tasks";
    page: "/api/projects/:projectId/sessions/:sessionId/tasks";
  };
  "routes/api.projects.$projectId.sessions.$sessionId.tasks.$taskId.notes.ts": {
    id: "routes/api.projects.$projectId.sessions.$sessionId.tasks.$taskId.notes";
    page: "/api/projects/:projectId/sessions/:sessionId/tasks/:taskId/notes";
  };
  "routes/api.projects.$projectId.sessions.$sessionId.tasks.$taskId.ts": {
    id: "routes/api.projects.$projectId.sessions.$sessionId.tasks.$taskId";
    page: "/api/projects/:projectId/sessions/:sessionId/tasks/:taskId";
  };
  "routes/api.sessions.$sessionId.ts": {
    id: "routes/api.sessions.$sessionId";
    page: "/api/sessions/:sessionId";
  };
  "routes/api.sessions.$sessionId.agents.ts": {
    id: "routes/api.sessions.$sessionId.agents";
    page: "/api/sessions/:sessionId/agents";
  };
  "routes/api.sessions.$sessionId.configuration.ts": {
    id: "routes/api.sessions.$sessionId.configuration";
    page: "/api/sessions/:sessionId/configuration";
  };
  "routes/api.sessions.$sessionId.history.ts": {
    id: "routes/api.sessions.$sessionId.history";
    page: "/api/sessions/:sessionId/history";
  };
  "routes/api.sessions.$sessionId.files.ts": {
    id: "routes/api.sessions.$sessionId.files";
    page: "/api/sessions/:sessionId/files";
  };
  "routes/api.sessions.$sessionId.files.$path.ts": {
    id: "routes/api.sessions.$sessionId.files.$path";
    page: "/api/sessions/:sessionId/files/*";
  };
  "routes/api.provider.catalog.ts": {
    id: "routes/api.provider.catalog";
    page: "/api/provider/catalog";
  };
  "routes/api.provider.instances.ts": {
    id: "routes/api.provider.instances";
    page: "/api/provider/instances";
  };
  "routes/api.provider.instances.$instanceId.ts": {
    id: "routes/api.provider.instances.$instanceId";
    page: "/api/provider/instances/:instanceId";
  };
  "routes/api.provider.instances.$instanceId.test.ts": {
    id: "routes/api.provider.instances.$instanceId.test";
    page: "/api/provider/instances/:instanceId/test";
  };
  "routes/api.threads.$threadId.message.ts": {
    id: "routes/api.threads.$threadId.message";
    page: "/api/threads/:threadId/message";
  };
  "routes/api.threads.$threadId.approvals.pending.ts": {
    id: "routes/api.threads.$threadId.approvals.pending";
    page: "/api/threads/:threadId/approvals/pending";
  };
  "routes/api.threads.$threadId.approvals.$toolCallId.ts": {
    id: "routes/api.threads.$threadId.approvals.$toolCallId";
    page: "/api/threads/:threadId/approvals/:toolCallId";
  };
  "routes/api.filesystem.list.ts": {
    id: "routes/api.filesystem.list";
    page: "/api/filesystem/list";
  };
  "routes/api.debug.console.ts": {
    id: "routes/api.debug.console";
    page: "/api/debug/console";
  };
};