// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/docs': {
    params: {};
  };
  '/play': {
    params: {};
  };
  '/font-test': {
    params: {};
  };
  '/speech-demo': {
    params: {};
  };
  '/sentry-test': {
    params: {};
  };
  '/project/:projectId': {
    params: {
      projectId: string;
    };
  };
  '/project/:projectId/session/:sessionId': {
    params: {
      projectId: string;
      sessionId: string;
    };
  };
  '/project/:projectId/session/:sessionId/agent/:agentId': {
    params: {
      projectId: string;
      sessionId: string;
      agentId: string;
    };
  };
  '/api/health': {
    params: {};
  };
  '/api/events/stream': {
    params: {};
  };
  '/api/threads/:threadId/message': {
    params: {
      threadId: string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page:
      | '/'
      | '/docs'
      | '/play'
      | '/font-test'
      | '/speech-demo'
      | '/sentry-test'
      | '/project/:projectId'
      | '/project/:projectId/session/:sessionId'
      | '/project/:projectId/session/:sessionId/agent/:agentId'
      | '/api/health'
      | '/api/events/stream'
      | '/api/threads/:threadId/message';
  };
  'routes/_index.tsx': {
    id: 'routes/_index';
    page: '/';
  };
  'routes/docs.tsx': {
    id: 'routes/docs';
    page: '/docs';
  };
  'routes/play.tsx': {
    id: 'routes/play';
    page: '/play';
  };
  'routes/font-test.tsx': {
    id: 'routes/font-test';
    page: '/font-test';
  };
  'routes/speech-demo.tsx': {
    id: 'routes/speech-demo';
    page: '/speech-demo';
  };
  'routes/sentry-test.tsx': {
    id: 'routes/sentry-test';
    page: '/sentry-test';
  };
  'routes/project.$projectId.tsx': {
    id: 'routes/project.$projectId';
    page:
      | '/project/:projectId'
      | '/project/:projectId/session/:sessionId'
      | '/project/:projectId/session/:sessionId/agent/:agentId';
  };
  'routes/project.$projectId.session.$sessionId.tsx': {
    id: 'routes/project.$projectId.session.$sessionId';
    page:
      | '/project/:projectId/session/:sessionId'
      | '/project/:projectId/session/:sessionId/agent/:agentId';
  };
  'routes/project.$projectId.session.$sessionId.agent.$agentId.tsx': {
    id: 'routes/project.$projectId.session.$sessionId.agent.$agentId';
    page: '/project/:projectId/session/:sessionId/agent/:agentId';
  };
  'routes/api.health.tsx': {
    id: 'routes/api.health';
    page: '/api/health';
  };
  'routes/api.events.stream.tsx': {
    id: 'routes/api.events.stream';
    page: '/api/events/stream';
  };
  'routes/api.threads.$threadId.message.tsx': {
    id: 'routes/api.threads.$threadId.message';
    page: '/api/threads/:threadId/message';
  };
};
